Waitlist table
openpodcast/connect pull request #4
Opened 2023-05-23 11:40 UTC by mre

Whenever we receive new credentials through `connect`, we store them in an encrypted table called the waitlist.

2023-05-23 12:54 UTC, woolfg requested changes
approach looks good

2023-05-23 12:54 UTC, woolfg commented on api/src/db/AuthRepository.ts
> +        const insertStmt = `INSERT INTO podcastConnectWaitlist (
no need to setup the prepared statement again, you can reuse the previous one.

2023-05-23 12:54 UTC, woolfg commented on api/src/db/AuthRepository.ts
> +        return await Promise.all(
we should think about defining somehow to not encrypt a value, e.g. webstationid as it simplifies debugging if those non critical values are stored as plain text in the db

2023-05-25 09:50 UTC, mre commented
Tested locally and works as expected. Needed to add `localhost:3001` to the list of allowed hosts for CORS.

2023-05-25 09:51 UTC, merged